version: '3'
services:
  flask:
    build: .
    restart: always
    ports:
      - '8000:5000'
    environment:
      - DATABASE_URL=mysql+pymysql://microblog:12345678@dbserver/microblog
  dbserver:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db-data:/var/lib/mysql/data
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=microblog
      - MYSQL_USER=microblog
      - MYSQL_PASSWORD=12345678
  adminer:
    image: adminer
    restart: always
    ports:
      - 1234:8080
volumes:
  db-data: