version: '3'
services:
  flask:
    build: .
    # restart: always
    ports:
      - '8000:5000'
    # environment:
      # - DATABASE_URL=mysql
  # mysql:
    # image: 'mysql'
    # restart: always
    # environment:
      # - MYSQL_ROOT_PASSWORD
      